language: python
sudo: false
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=py2.7-unittest
  - TOXENV=py2.7-integration
  - TOXENV=py2.7-experiments
  - TOXENV=style
  - TOXENV=coverage
  - TOXENV=2to3
